# Generated by Django 3.1.7 on 2021-04-09 04:29

from django.db import migrations
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('django_model', '0005_auto_20210408_1119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='parent',
            field=mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='django_model.category'),
        ),
        migrations.DeleteModel(
            name='SubCategory',
        ),
    ]
