# Generated by Django 3.2 on 2021-05-03 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='House',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flat', models.IntegerField()),
                ('area', models.DecimalField(decimal_places=2, max_digits=4)),
                ('room', models.IntegerField()),
                ('address', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'house',
                'ordering': ['address'],
            },
        ),
    ]
