# Generated by Django 3.2 on 2021-05-03 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='house',
            name='area',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4),
        ),
    ]
