# Generated by Django 3.2 on 2021-05-03 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_house_area'),
    ]

    operations = [
        migrations.AlterField(
            model_name='house',
            name='area',
            field=models.DecimalField(decimal_places=2, max_digits=4, null=True),
        ),
    ]
