# Generated by Django 3.2 on 2021-04-19 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateField(auto_now_add=True)),
                ('updated_on', models.DateField()),
                ('order', models.IntegerField()),
                ('payment_choices', models.CharField(choices=[('COD', 'Cash On Delivery'), ('PGT', 'Payment Gateway')], max_length=3)),
                ('date', models.DateField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'payment',
                'db_table': 'payment_info',
                'ordering': ['date'],
            },
        ),
    ]
