# Generated by Django 3.2 on 2021-04-19 05:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment_api', '0002_alter_invoice_updated_on'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='invoice',
            options={'ordering': ['created_on'], 'verbose_name': 'payment'},
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='date',
        ),
    ]
