# Generated by Django 3.1.7 on 2021-04-05 09:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('django_model', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('sku', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='django_model.sku')),
                ('quantity', models.IntegerField()),
                ('country', models.CharField(max_length=15)),
                ('shipping_date', models.DateField()),
                ('manufacture_date', models.DateField()),
                ('expiry_date', models.DateField()),
            ],
        ),
    ]
