# Generated by Django 3.1.7 on 2021-04-05 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_model', '0002_batch'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='batch',
            options={'ordering': ['country']},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelTable(
            name='batch',
            table='Batch',
        ),
    ]
